title: Twilight Sword
description: Wiki do sistema Twilight Sword
theme: just-the-docs
color_scheme: dark
url: https://lucaommsantos-gif.github.io
baseurl: "/twilight-sword-traducao"

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
